name: Build and Push Docker Images for Microfrontends

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        microfrontend: [admin, inventory, sales, shell, wearhouse]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.microfrontend }}-${{ hashFiles('./projects/${{ matrix.microfrontend }}/Dockerfile.${{ matrix.microfrontend }}') }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.microfrontend }}-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image for ${{ matrix.microfrontend }}
        run: |
          docker build -f ./projects/${{ matrix.microfrontend }}/Dockerfile.${{ matrix.microfrontend }} -t ghcr.io/${{ github.repository_owner.toLowerCase() }}/${{ matrix.microfrontend }}-ui:${{ github.sha }} .

      - name: Push Docker image for ${{ matrix.microfrontend }}
        run: |
          docker push ghcr.io/${{ github.repository_owner.toLowerCase() }}/${{ matrix.microfrontend }}-ui:${{ github.sha }}

      - name: Push Docker image with 'latest' tag
        run: |
          docker tag ghcr.io/${{ github.repository_owner.toLowerCase() }}/${{ matrix.microfrontend }}-ui:${{ github.sha }} ghcr.io/${{ github.repository_owner.toLowerCase() }}/${{ matrix.microfrontend }}-ui:latest
          docker push ghcr.io/${{ github.repository_owner.toLowerCase() }}/${{ matrix.microfrontend }}-ui:latest

      - name: Run Docker Scout vulnerability scan for ${{ matrix.microfrontend }}
        uses: docker/scout-action@v1
        with:
          dockerfile: ./projects/${{ matrix.microfrontend }}/Dockerfile.${{ matrix.microfrontend }}
